ansible_user: ubuntu
ansible_ssh_private_key_file: /var/lib/jenkins/tfkey.pem
ansible_ssh_common_args: >-
  -o StrictHostKeyChecking=no
  -o UserKnownHostsFile=/dev/null
  -o ProxyCommand="ssh -i /var/lib/jenkins/tfkey.pem
                   -o StrictHostKeyChecking=no
                   -o UserKnownHostsFile=/dev/null
                   -W %h:%p ubuntu@3.95.134.148"
ansible_become: yes
ansible_become_method: sudo
