ansible_user: ubuntu
ansible_ssh_private_key_file: /var/lib/jenkins/tfkey.pem
ansible_ssh_common_args: >-
ansible_ssh_common_args: >-
  -o StrictHostKeyChecking=no
  -o ProxyCommand="ssh -i /var/lib/jenkins/tfkey.pem -W %h:%p ubuntu@3.89.250.158"
ansible_become: yes
ansible_become_method: sudo

