plugin: amazon.aws.aws_ec2
regions:
  - us-east-1
keyed_groups:
  - key: tags.Role
    prefix: tag_Role
hostnames:
  - private-ip-address
compose:
  ansible_host: private_ip_address
  ansible_user: ubuntu
  ansible_ssh_private_key_file: /var/lib/jenkins/tfkey.pem
  ansible_ssh_common_args: "-o ProxyCommand='ssh -W %h:%p -i /var/lib/jenkins/tfkey.pem ubuntu@{{ bastion_ip }}' -o StrictHostKeyChecking=no"


